class TipsContent{
  TipsContent._();
  static final kTipsFlexible = "Hai PWers!\n\nPerkenalkan kami dari tadi, Eh aku Adisty dari Paruhwaktu!\n\nPasti kalian bertanya-tanya kayak gini:\n'Apa sih Paruhwaktu itu? Penting banget buat hidup gue?'\nParuhwaktu itu merupakan sebuah aplikasi yang dapat memberikan kesempatan kepada masyarakat untuk bekerja paruh waktu sebagai Digital Customer Service.\n\nIntinya nih, Paruhwaktu memberikan Kamu kesempatan mengisi waktu luangmu untuk mendapatkan penghasilan tambahan.Hanya cukup dengan menggunakan handphone, di mana pun Kamu berada Kamu dapat bekerja menjadi agent PW!\n\nOiya, Paruhwaktu menyediakan 2 jenis pekerjaan yang dapat Kamu pilih sesuai bidang yang Kamu inginkan yaitu Digital Customer Service dan Digital Sales Admin.\n\nSegitu dulu ya, Adisty lelah ngetiknya!";
  static final kTipsCS = "Jumpa lagi bareng Adisty, PWers!\n\nYuk, kuliah 2 SKS mengenai Customer Service! 😂\n\nApa sih Customer Service itu?\n\n\Pasti kalian udah sering denger kan malah sering banget curhat ke Customer Service karena ga ada tempat lain buat dicurhatin, yekaan?! Jomblo boleh tapi jgn gitu2 banget ya 🤭\n\nJadi Customer Service itu merupakan kegiatan yang ditujukan untuk memberikan kepuasan pelanggan melalui pelayanan. Pelayanan tersebut mencakup semua tahapan proses untuk memenuhi permintaan dan kebutuhan konsumen.";
  static final kTipsMoney = "PWers, Butuh uang tambahan? Sama dong, Adisty jugaaaa! 😢\n\nTapi boong deng, Adisty mah kan udah jadi agent Paruhwaktu! Jadi rekeningnya gendut laaaah!\n\nMakanya gabung yuk di Paruhwaktu, daripada waktu luang terbuang, mending dijadiin uang!\n\nKalian bisa atur sendiri pendapatan kalian, makin rajin makin cepet bisa lamar calon pasangan yang sudah bertahun-tahun terhipnotis janji manismu. 😂\n\nWith ❤,\nAdisty";
  static final promo1 = '''Bagi Anda yang belum pernah mendengar, apa sih sebetulnya Mimamori itu? Untuk diketahui, Mimamori merupakan sebuah Fleet Management System yang berasal dari Isuzu. Dengan sistem ini akan memudahkan kustomer memastikan pengoperasian truknya secara aman dan efisien. Sejatinya teknologi ini sudah lama dikenalkan Isuzu Jepang pada 2001 dengan sebutan Mimamori-Kun.
    \nNah, mimamori dapat diaplikasikan di unit Isuzu GIGA yang merupakan truk medium terdepan yang sudah mengusung mesin commonrail dan sudah dilengkapi dengan ECU (Electronic Control Unit) dan DRM (Data Record Module). Mimamori dapat merekam data pengoperasian, kemudian mengirimkannya secara berkala ke server yang dapat diakses melaui website melalui PC, Laptop, atau Smartphone.
    \nTruk adalah aset produktif yang cukup bernilai tinggi dan tak jarang membawa muatan yang bernilai tinggi pula. Untuk itu, diperlukan cara pengoperasian yang aman sehingga terhindar dari kecelakaan, breakdown, dan hal tidak diinginkan lainnya. Di sisi lain, biaya terbesar bagi perusahaan transportasi untuk mengoperasikan truk adalah biaya bahan bakar. Untuk itu, diperlukan cara pengoperasian truk yang efisien dan ekonomis. Dari sini lah Mimamori hadir untuk memberikan pelayanan kepada kustomer Isuzu yang ingin melakukan full monitoring kepada unit truk yang dimiliki.
    \nMimamori dilengkapi dengan fitur GPS sehingga Customer dapat memonitor lokasi kendaraan secara real time. Customer juga dapat melihat sejarah perjalanan truk tersebut. Mimamori juga terkoneksi dengan GoogleMaps sehingga dapat bermanfaat untuk melihat kepadatan lalu lintas dan pemilihan rute perjalanan yang efisien. Mimamori dilengkapi pula dengan Geofence, untuk memagari lokasi sebagai tujuan atau sebagai lokasi yang tidak boleh dimasuki.
    \nKekuatan terbesar Mimamori terletak pada laporan mengenai kebiasaan mengemudi. Laporan-laporan ini berguna untuk memastikan pengemudi truk dapat mengoperasikan truk secara aman dan efisien. Kustomer dapat memonitor konsumsi bahan bakar, kebiasaan cara pemilihan kecepatan, kebiasaan idling, kebiasaan penggunaan pedal gas, kebiasaan pengereman, kebiasaan pemilihan rpm mesin dan kebiasaan pemindahan gigi.''';
  static final promo2 = '''Isuzu telah menunjukkan keunggulan kompetitifnya sekali lagi, sebagai best selling brand di banyak pasar global pada 2017. Torehan tersebut berdasarkan angka penjualan yang dikompilasi oleh perusahaan baru-baru ini.
    \nDi Jepang, N Series, yang dikenal secara lokal sebagai Isuzu Elf, mampu menjaring pangsa pasar 39,7% untuk segmentasi truk dengan muatan di atas dua hingga tiga ton. Hal ini turut memperpanjang serangkaian capaian selama 17 tahun berturut-turut dan selalu menjadi No. 1 kecuali di tahun 1970.
    \nDi Hong Kong, Isuzu menduduki semua pasar truk (3,5 – 38 ton GVW) dengan pangsa pasar 59,7%, memperpanjang capaian sebagai merek No. 1 selama 38 tahun. Inilah salah satu yang terlama di antara Isuzu Group. Distributor Triangle Motors merayakan pencapaian pada 2 Februari, dengan sekitar 150 karyawan dan jajaran direksi dari Dah Chong Hong Holdings. Isuzu Chairman, Susumu Hosoi datang dari Jepang untuk memberikan pidato. Dia mengucapkan terima kasih kepada Triangle Motors untuk terus meningkatkan penjualan dan layanan selama kemitraan yang panjang dengan Isuzu sejak tahun 1973.
    \nDi Thailand, Isuzu memiliki pangsa pasar 36,6% sehingga memimpin segmen pick-up untuk pertama kalinya sejak 2005. Hal ini merupakan jerih payah distributor Isuzu, Tri Petch Isuzu Sales yang tak kenal lelah untuk mempromosikan kendaraan Isuzu, yang tangguh dan hemat bahan bakar. Perusahaan meningkatkan kegiatan promosi untuk menandai peringatan 60 tahun penjualan Isuzu di negara tersebut.
    \nSetelah Isuzu merilis D-MAX baru, dengan tampang depan yang didesain ulang pada November lalu, turut membantu Isuzu dalam merebut kembali posisi teratas. Selain itu, Isuzu mengantongi penjualan apik kendaraan komersial dari muatan dua ton selama 44 tahun berturut-turut. Bukti yang luar biasa dari popularitas Isuzu yang terus bertahan.
    \nDi Peru, light duty truck Isuzu (3,5 – 9,35 ton GVW) didistribusikan oleh General Motors Peru mencapai pangsa pasar 18,8%. Mereka memimpin pasar di kategori ini untuk pertama kalinya. Acara promosi berfokus pada tempat-tempat yang sering dikunjungi oleh pengemudi truk, seperti pasar barang pecah belah. Animo pengunjung sangat baik, saat melihat demo truk Isuzu sembari menikmati hiburan musik. Sebelumnya acara tersebut telah diumumkan melalui media sosial, sehingga turut menciptakan kehadiran yang kuat, demi eksposur yang baik bagi merek Isuzu.''';
  static final promo3 = '''Ajang Gaikindo Indonesia International Auto Show (GIIAS 2018) menjadi titik acuan penting bagi industri otomotif Tanah Air. Yohanes Nangoi, Ketua Umum Gaikindo bersama pemerintah menggunakan momen ini untuk mendeklarasikan standar Euro 4 bagi mesin bensin. Aturan emisi Euro 4 sudah dikeluarkan melalui Peraturan Menteri Lingkungan Hidup dan Kehutanan No. P20/MENLHK/SETJEN/KUM.1/3/2017. Mobil bermesin bensin berlaku mulai September 2018, sementara untuk mesin diesel efektif pada 10 Maret 2021. Penerapan Euro 4 bertujuan mengurangi pencemaran udara yang disebabkan emisi gas buang kendaraan bermotor.
    \n"Kami senang mendengar hal mengenai Euro 4 karena memang kita harus sama- sama mendukung kemajuan negara Indonesia. Bahkan negara- negara lain sudah melakukan itu seperti Singapura, Thailand, dan negara lainnya sudah beralih ke Euro 4 dan bahkan lebih. Isuzu sudah sangat siap dalam menghadapi regulasi pemerintah mengenai Euro 4, karena kami sudah memiliki engine yang mendukung Euro 4 sejak tahun 2011, yaitu engine common-rail," papar Ernando Demily, President Director PT Isuzu Astra Motor Indonesia.
    \nUntuk diketahui pula, bahan bakar standar yang mendukung spesifikasi Euro 4 harus sudah mengantongi nilai Research Octane Number yang disepakati, seperti RON 92, RON 95 serta Solar 51. Belum selesai di situ saja. Standar BBM tersebut juga tak boleh mengandung kadar sulfur lebih dari 50 part per milion (perbandingan konsentrasi zat terlarut dan pelarutnya).
    \nNah dalam kaitanya dengan standar baru itu, selain kesiapan produk, layanan purna jual bagi Isuzu juga menjadi penting. Salah satunya dari sisi kemampuan mekanik dalam menangani teknologi baru. Isuzu sudah terbiasa menangani teknologi common-rail. Hal ini dikuatkan dengan kemenangan mekanik Isuzu Indonesia dalam Isuzu World Technician Competition CV (Commercial Vehicle) Division atau I-1 Grand Prix yang ke-12 di Jepang.
    \n"Kemenangan tim mekanik Isuzu Indonesia ini membuktikan bahwa Isuzu Indonesia terus menerus berupaya memberikan pelayanan terbaik dalam hal After Sales Service, didukung oleh mekanik-mekanik yang handal. Isuzu Indonesia sangat tangguh menghadapi tantangan dimasa depan baik dengan product unggulan Isuzu, service dan feature-feature yang dikembangkan terus oleh Isuzu Indonesia," pungkasnya.''';
}